### ISSUE TITLE
Batch submission fails on extraction and breaks file

### ISSUE THREAD

**Issue by Jake3784** [seek4science/seek#1206]
**Describe the bug**
Recently when creating samples using the "new batch submission" feature, the data file gets stuck in queue for extracting the samples indefinitely. Besides not creating the samples, this also leads to an inability to manage or edit the data file as opening its page when signed in redirects to an error message (the data file page can be viewed when not signed in & the file may be downloaded).

**To Reproduce**
** I have not been able to recognize a difference between the instances where this error occurs and the instances where the submission works perfectly as intended ***

1. Go to 'Create'
2. Click on 'Sample'
3. Scroll down to the specific sample type
4. Click on 'New Batch Submission'
5. Click on 'Data file uploader' (Step 3)
6. Chose the file to be uploaded (have been using local)
7. Finish uploading the file
8. Open the page of the data file
9. Click on 'Extract Samples'
10. If the error occurs, the file will indefinitely be in queue for extraction

**Expected behavior**
After a period of time there should be an option to review samples to be extracted and then to finalize extraction.

**Screenshots**
Data file stuck in queue:
![fairdomQueue](https://user-images.githubusercontent.com/78221832/196502531-68007365-d160-4635-9664-bb5c473b77b8.png)

Error page that is thrown when trying to access data file [only for the uploader when signed in (previous page can no longer be seen)]
![fairdomErrorPage](https://user-images.githubusercontent.com/78221832/196502530-68b47b1c-b941-4b7d-a243-125e2df81fd2.png)

Data File Page for someone not signed in
![fairdomPublicPage](https://user-images.githubusercontent.com/78221832/196503480-5010d5c1-e723-4420-9d54-548313c68b3f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 106.0.1370.47

**Additional context**
There have been instances of batch submission working after this problem was first found.

**Comment by fbacall** [comment]
> this also leads to an inability to manage or edit the data file as opening its page when signed in redirects to an error message

I've corrected this now. Can you try extracting the samples again?

**Comment by Jake3784** [comment]
Yeah, it seems it is stuck on 'Sample extraction: Active'. For reference, there are 32 samples in the batch submission which in my experience is usually quite fast to extract.

**Comment by stuzart** [comment]
Hi @Jake3784 
I've been looking into this problem. I'm still not quite sure what went wrong. The extracted samples get put into a temporary file, but in this case it ended up as a blank file. I'm still trying to track down why that might have happened and prevent it leaving a blank file in the future if things go wrong. 
 
However, whilst investigating I reproduced the steps the job performs that runs, and it created the file of the correct size. So you should be able to proceed with the next steps of Reviewing and Storing the extracted samples.

In the meantime I will try and figure out what happened. From above it sounds like it happened twice and wasn't down to some freak event.

**Comment by Jake3784** [comment]
Thank you so much for your help. I was able to go ahead and finish extracting samples for two of the three instances where this problem arose. The final instance still doesn't work but the problem looks a little different. I'm able to select 'Extract Samples' and there is a message that 'Sample Extraction: Queued' but the page no longer gets stuck on this message. Instead, the message disappears after a few seconds and the process is seemingly terminated.

**Comment by stuzart** [comment]
It sounds like the last case is encountering the same problem as before. I deployed a very small partial fix, to avoid it creating the blank file that led to page crashing and prevents the ability to retry. This was just a quick fix, and I'm making more changes to report that something went wrong and also record the exception and report it to us.
If it is urgent I can force the 3rd datafile onto the next step, otherwise I will use it to try and reproduce the problem.
I'd strange because I've so far not been able to reproduce.

**Comment by Jake3784** [comment]
Nope, it's not particularly urgent. Feel free to continue using it as a test case.

**Comment by stuzart** [comment]
The underlying problem should be fixed now, so you should be able to extract your other samples.

I'm leaving the issue open, as I still want to add some further changes that improves the error reporting both to us and the user
